### ISSUE TITLE
添加自动ping服务器逻辑

### ISSUE THREAD

**Issue by linfulongnet** [yangjuncode/jsyrpc#6]

**Comment by yangjuncode** [comment]
5分钟内要发一次数据给后台以保持连接活动

**Comment by linfulongnet** [comment]
测试正常，在没有交互指令时，5分钟内ping一次数据
![image](https://user-images.githubusercontent.com/23325671/75211520-1faca680-57bf-11ea-8b05-c4218de0e65a.png)
